### PR TITLE
Patch/add bg colors

### PR DESCRIPTION
**Pull request by OPARA-PROSPER**
This is sample of what using the colors as background will look like

### CODE REVIEW

**Comment by larson-carter** [comment]
@OPARA-PROSPER Can you fix the merge conflicts so I can test our your amazing work?

**Comment by larson-carter** [comment]
@OPARA-PROSPER You also need to add the commit history for @bartekpacia as his work is going to be removed since you didn't tag the commit.

**Comment by OPARA-PROSPER** [comment]
@larson-carter woooohhh...

I actually checkout from his branch so his commits are not lost

**Comment by larson-carter** [comment]
> @larson-carter woooohhh...
> 
> I actually checkout from his branch so his commits are not lost

https://github.com/MLH-Fellowship/MLH-OH-MY-ZSH-THEME/pull/8/commits/76cd91c8b5df841a0c83095f68d1433c2acfffed

**Comment by bartekpacia** [comment]
That's how it looks like.
Screenshot 2020-06-15 at 10 23 26 PM

I suggest letting the user customize whether he wants foreground or background colors.

**Comment by bartekpacia** [comment]
@OPARA-PROSPER I have added the option for the user to customize all the colors.
Now, changing text foreground color to be a background color is as easy as changing `FG` to `BG`.
Here's [the commit](https://github.com/MLH-Fellowship/MLH-OH-MY-ZSH-THEME/commit/b3c3ea07d8c41fbae43d7ec9b5e04c544cd1905b).

Do you agree to close this? @larson-carter @OPARA-PROSPER

**Comment by OPARA-PROSPER** [comment]
> Do you agree to close this? @larson-carter @OPARA-PROSPER

Makes sense, I have been thinking about the output of using BG and prolly FG is a better route to follow. The colors have high contrast and are noisy as background colors

**Comment by bartekpacia** [comment]
that's right, using the current colors as the background colors looks bad, but they're very easy to customize.
Are there colors that look well in both light/dark theme and both as foreground/background and match the MLH logo?

**Comment by OPARA-PROSPER** [comment]
> that's right, using the current colors as the background colors looks bad, but they're very easy to customize.
> Are there colors that look well in both light/dark theme and both as foreground/background and match the MLH logo?

Black will make sense for the yellow background, the white font is cool on both red and blue Background

**Comment by bartekpacia** [comment]
so do you want to change the default colors?

**Comment by OPARA-PROSPER** [comment]
> so do you want to change the default colors?

Prolly use another shade of yellow 🤔, might improve the contrast and not cause any change to default colors.

If it doesn't work, we could just close this PR

**Comment by bartekpacia** [comment]
Larson and me have tried quite a few shades of yellow and came to a conclusion that `[220]` works best. So I'd lean towards closing this.

**Comment by OPARA-PROSPER** [comment]
Makes sense

**Pull request closed without merging**
